export default [
    'DBMS_CRYPTO',
    'DBMS_DEBUG',
    'UTL_ENCODE',
    'DBMS_LOB',
    'DBMS_LOCK.SLEEP',
    'DBMS_METADATA.GET_DDL',
    'DBMS_OUTPUT',
    'DBMS_RANDOM',
    'DBMS_SQL',
    'DBMS_XA',
    'ODCIArgDesc.ArgType',
    'ODCIEnv',
    'ODCIFuncInfo.Flags',
    'ODCIIndexAlter parameter alter_option',
    'ODCIIndexInfo',
    'ODCIPredInfo.Flags',
    'ODCIQueryInfo.Flags',
    'ODCIStatsOptions',
    'UTL_I18N',
    'UTL_RAW',
    'SA_SYSDBA',
    'SA_COMPONENTS',
    'SA_LABEL_ADMIN',
    'SA_POLICY_ADMIN',
    'SA_USER_ADMIN.SET_LEVELS',
    'SA_SESSION',
  ];
  